name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.7
      - run: npm install
      - run: npm run build
      - run: ls

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "the-bookworm"
        with:
          args: deploy
